// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMrS9SvewOBzbYEvsoy6VCjfC7cYbJ1A',
    appId: '1:21788783981:web:af7a4b31639e400127d664',
    messagingSenderId: '21788783981',
    projectId: 'empapp-bd83f',
    authDomain: 'empapp-bd83f.firebaseapp.com',
    storageBucket: 'empapp-bd83f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdndOs-Aqfay_bLFKRsevouEQS-pCseQ4',
    appId: '1:21788783981:android:7e5ead47b4aeee7c27d664',
    messagingSenderId: '21788783981',
    projectId: 'empapp-bd83f',
    storageBucket: 'empapp-bd83f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mU5pqtNbIlURkRym95EUGDy5JHilBRg',
    appId: '1:21788783981:ios:a16c2b4d83a8785727d664',
    messagingSenderId: '21788783981',
    projectId: 'empapp-bd83f',
    storageBucket: 'empapp-bd83f.firebasestorage.app',
    iosBundleId: 'com.example.empApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwMrS9SvewOBzbYEvsoy6VCjfC7cYbJ1A',
    appId: '1:21788783981:web:8aa7dec583bb407d27d664',
    messagingSenderId: '21788783981',
    projectId: 'empapp-bd83f',
    authDomain: 'empapp-bd83f.firebaseapp.com',
    storageBucket: 'empapp-bd83f.firebasestorage.app',
  );
}
